version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - gosec
  exclusions:
    rules:
      - path: "_test.go"
        linters:
          - gosec

formatters:
  enable:
    - gofumpt
    - goimports
